version: '3'
services: 
  server:
    container_name: server-container-final
    restart: always
    build: ./server
    ports: 
      - "5000:5000"

  client:
    container_name: client-container-final
    restart: always
    build: ./client
    ports: 
      - "3000:3000"
    depends_on: 
      - server
